r"""
This file was *autogenerated* from LinearRegression.tex with sagetex.sty
version 2015/08/26 v3.0-92d9f7a. It contains the contents of all the
sageexample environments from LinearRegression.tex. You should be able to
doctest this file with "sage -t LinearRegression_doctest.sage".

It is always safe to delete this file; it is not used in typesetting your
document.

Sage commandline, line 106::

sage: 2+2

"""
